# Generated by Django 5.0.7 on 2024-08-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, upload_to='3d_models/')),
                ('description', models.TextField()),
                ('total_area', models.FloatField()),
                ('effective_area', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.JSONField()),
                ('blueprint', models.FileField(upload_to='blueprints/')),
                ('exterior_images', models.ImageField(blank=True, upload_to='exterior_images/')),
                ('interior_images', models.ImageField(blank=True, upload_to='interior_images/')),
            ],
        ),
    ]
