# Generated by Django 5.1.1 on 2024-09-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model_3d', models.FileField(blank=True, upload_to='3d_models/')),
                ('description', models.TextField()),
                ('total_area', models.FloatField()),
                ('effective_area', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blueprint', models.FileField(upload_to='blueprints/')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ImageField(upload_to='external_photos/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_photos', to='Main.house')),
            ],
        ),
        migrations.CreateModel(
            name='InternalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ImageField(upload_to='internal_photos/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_photos', to='Main.house')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_area', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Main.house')),
            ],
        ),
    ]
