# Generated by Django 5.0.7 on 2024-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='exterior_images',
        ),
        migrations.RemoveField(
            model_name='house',
            name='interior_images',
        ),
        migrations.AddField(
            model_name='house',
            name='exterior_photos',
            field=models.ImageField(blank=True, upload_to='exterior_photos/'),
        ),
        migrations.AddField(
            model_name='house',
            name='interior_photos',
            field=models.ImageField(blank=True, upload_to='interior_photos/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='model_3d',
            field=models.FileField(upload_to='3d_models/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
