# Generated by Django 5.0.7 on 2024-08-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_house_exterior_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='exterior_photos',
        ),
        migrations.RemoveField(
            model_name='house',
            name='interior_photos',
        ),
        migrations.RemoveField(
            model_name='house',
            name='rooms',
        ),
        migrations.AlterField(
            model_name='house',
            name='model_3d',
            field=models.FileField(blank=True, upload_to='3d_models/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ExteriorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='exterior_photos/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_photos', to='Main.house')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='interior_photos/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_photos', to='Main.house')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='Main.house')),
            ],
        ),
    ]
