# Generated by Django 5.0.7 on 2024-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
